### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'configs'

### ISSUE THREAD

**Issue by HumanKR** [SoonbeomChoi/BEGAN-Sing#2]
![image](https://user-images.githubusercontent.com/45139720/115994141-b3227700-a610-11eb-8081-0b54fc8f5887.png)
I'm using windows 10 x64 and python 3.6.
I have a problem when I Preprocessing on cmd and pycharm, etc...
I have no idea how to fix this.
if you explain to me with korean, i can understand much better.

**Comment by SoonbeomChoi** [comment]
Thanks for sharing the problem.
The problem was due to my mistake and I just fixed the issue.
Please check whether the problem is solved :)

**Comment by HumanKR** [comment]
Alright! is working fine!
but and it seems have to fix this too.
![image](https://user-images.githubusercontent.com/45139720/116044008-5c1db000-a6ab-11eb-9208-8c0c7b290f75.png)
It's seems have a problem with utf-8.
Like a txt file about "반짝반짝 작은별" you know.
So i just fix that on preprocess.py at line 19 like this.
`text_file = open(filename, encoding='UTF8')`

Thank you for help!
I was unexpected to answer about issues :D
because this codes... just unchanged about 1 year.
Just written comment with hope to someone help this problem... hehe
Thanks again, I want to be a cool at programing like you.

I'm gonna go a little further and close the comment myself. Have a nice day!

**Comment by HumanKR** [comment]
If someone reading this and not have a high-end pc, using windows 10, not good at python.
Let me give you some tip.

Before started, my pc spec is,
i7 4790
16gb ram
GTX 970 4gb

Install torch 1.6.0 version.
He used torch==1.5.0 but Torchaudio 0.5 is not supported on windows. (or i can't find lol)
So we have to install pytorch 1.6.0 for torchaudio 0.6 and it's working too!
Maybe... you should find .whl files on this site.
https://download.pytorch.org/whl/torch_stable.html

And buy cool graphic card.
I know graphic card is still expensive. I'm tired of the high prices too.
but he using 'RTX2080 Ti'.
um... we haven't enough VRAM right?
I changed 'batch_size' 32 to 8, and there is no more OOM (out of memory).
and 1 epoch, take 15 second. NO WAY. (On the basis of sample)
That's why I told you buy cool graphic card. not a old things.

**Comment by SoonbeomChoi** [comment]
> Alright! is working fine!
> but and it seems have to fix this too.
> ![image](https://user-images.githubusercontent.com/45139720/116044008-5c1db000-a6ab-11eb-9208-8c0c7b290f75.png)
> It's seems have a problem with utf-8.
> Like a txt file about "반짝반짝 작은별" you know.
> So i just fix that on preprocess.py at line 19 like this.
> `text_file = open(filename, encoding='UTF8')`
> 
> Thank you for help!
> I was unexpected to answer about issues :D
> because this codes... just unchanged about 1 year.
> Just written comment with hope to someone help this problem... hehe
> Thanks again, I want to be a cool at programing like you.
> 
> I'm gonna go a little further and close the comment myself. Have a nice day!

Thanks for reporting the issue and I just applied the change.
Also thanks for your interest in this repo and it is happy to get feedbacks :)
